version: "3"
services:
  app:
    image: node:lts
    ports:
      - "8000:8000"
    command: "sh -c 'cd /app && npm install && npm run start:dev'"
    volumes:
      - ./server:/app
  front:
    image: node:lts
    ports:
      - "3000:3000"
    command: "sh -c 'cd /front && npm install && npm run start'"
    volumes:
      - ./front:/front
